#!/bin/bash

# Define base directories
BASE_DIR=~/Library/Containers/com.utmapp.UTM/Data/Documents
SNAPSHOTS_DIR=$BASE_DIR/Snapshots

# Create Snapshots directory if it doesn't exist
mkdir -p $SNAPSHOTS_DIR

create() {
    VM_NAME=$1
    TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
    SNAPSHOT_NAME="${VM_NAME}_${TIMESTAMP}.tar.gz"
    
    VM_PATH=$(find $BASE_DIR -type d -name "$VM_NAME.utm" -print -quit)
    
    if [ -d "$VM_PATH" ]; then
        VM_DIR_NAME=$(basename "$VM_PATH")
        tar -czvf $SNAPSHOTS_DIR/$SNAPSHOT_NAME -C $BASE_DIR $VM_DIR_NAME
        echo "Snapshot created: $SNAPSHOT_NAME"
    else
        echo "VM directory $VM_NAME.utm does not exist."
    fi
}

revert() {
    VM_NAME=$1
    SNAPSHOT_FILE=$2

    if [ -z "$VM_NAME" ] || [ -z "$SNAPSHOT_FILE" ]; then
        echo "Usage: $0 revert <VM_NAME> <SNAPSHOT_FILE>"
        return
    fi

    SNAPSHOT_PATH=$SNAPSHOTS_DIR/$SNAPSHOT_FILE
    VM_PATH=$(find $BASE_DIR -type d -name "$VM_NAME.utm" -print -quit)

    if [ -f "$SNAPSHOT_PATH" ]; then
        if [ -d "$VM_PATH" ]; then
            rm -rf "$VM_PATH"
        fi
        tar -xzvf $SNAPSHOT_PATH -C $BASE_DIR
        echo "Reverted $VM_NAME to snapshot $SNAPSHOT_FILE"
    else
        echo "Snapshot file $SNAPSHOT_FILE does not exist."
    fi
}

ls_snapshots() {
    VM_NAME=$1

    if [ -z "$VM_NAME" ]; then
        ls -l $SNAPSHOTS_DIR
    else
        ls -l $SNAPSHOTS_DIR | grep "$VM_NAME"
    fi
}

prune() {
    VM_NAME=$1
    RETENTION=$2

    if [ -z "$VM_NAME" ] || [ -z "$RETENTION" ]; then
        echo "Usage: $0 prune <VM_NAME> <RETENTION>"
        return
    fi

    SNAPSHOTS=$(ls $SNAPSHOTS_DIR | grep "$VM_NAME" | sort -r)
    COUNTER=0

    for SNAPSHOT in $SNAPSHOTS; do
        COUNTER=$((COUNTER + 1))
        if [ $COUNTER -gt $RETENTION ]; then
            delete_snapshot $SNAPSHOT
        fi
    done
}

delete_snapshot() {
    SNAPSHOT_FILE=$1

    if [ -z "$SNAPSHOT_FILE" ]; then
        echo "Usage: $0 delete <SNAPSHOT_FILE>"
        return
    fi

    # Check if snapshot file exists
    if [ -f "$SNAPSHOTS_DIR/$SNAPSHOT_FILE" ]; then
        rm -f $SNAPSHOTS_DIR/$SNAPSHOT_FILE
        echo "Deleted snapshot: $SNAPSHOT_FILE"
    else
        echo "Snapshot file $SNAPSHOT_FILE does not exist."
    fi
}

# Main script
COMMAND=$1

case $COMMAND in
    create)
        if [ -z "$2" ]; then
            echo "Usage: $0 create <VM_NAME>"
        else
            create $2
        fi
        ;;
    revert)
        if [ -z "$2" ] || [ -z "$3" ]; then
            echo "Usage: $0 revert <VM_NAME> <SNAPSHOT_FILE>"
        else
            revert $2 $3
        fi
        ;;
    ls)
        if [ -z "$2" ]; then
            ls_snapshots
        else
            ls_snapshots $2
        fi
        ;;
    prune)
        if [ -z "$2" ] || [ -z "$3" ]; then
            echo "Usage: $0 prune <VM_NAME> <RETENTION>"
        else
            prune $2 $3
        fi
        ;;
    delete)
        if [ -z "$2" ]; then
            echo "Usage: $0 delete <SNAPSHOT_FILE>"
        else
            delete_snapshot $2
        fi
        ;;
    *)
        echo "Usage: $0 {create|revert|ls|prune|delete}"
        ;;
esac
